default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db  # Change this from 127.0.0.1 to the service name of your DB container
  port: 3306

development:
  <<: *default
  database: book_reminder_development

test:
  <<: *default
  database: book_reminder_test
